app/myblog/myapp/urls.py
from django.urls import path, include
from .views import Index, PostCreate, PostDelete, PostDetail, PostUpdate, PostList, Login, Logout, SignUp, AddLike, CategoryList, CategoryDetail, SearchPost

app_name = 'myapp'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('post_create/', PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', PostDelete.as_view(), name='post_delete'),
    path('post_list/', PostList.as_view(), name='post_list'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('like/<int:post_id>/', AddLike, name='addlike'),
    path('category_list', CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name>/', CategoryDetail.as_view(), name='category_detail'),
    path('search/', SearchPost, name='search_post'),
]

app/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/myblog/myapp/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('category_name', max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def count_posts_belong_to(self):
        n = Post.objects.filter(category = self).count()
        return n
    
    def __str__(self):
        return self.name
    

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('title', max_length=50)
    content = models.TextField('content')
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    

class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="Post", on_delete=models.PROTECT)
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.PROTECT)

app/myblog/myapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'thumbnail')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        
            
            
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SearchForm(forms.Form):
    search_word = forms.CharField(min_length=1, max_length=50, label='', required=False)
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    

app/myblog/myapp/views.py
from sqlite3 import paramstyle
from django.utils import timezone
from django.shortcuts import redirect, render, resolve_url
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.core.paginator import Paginator

from .models import Post, Like, Category
from .forms import PostForm, LoginForm, SignUpForm, SearchForm


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        post = Post.objects.get(id = self.kwargs['pk'])
        return post.author == self.request.user


class OnlyPostCreate(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        return self.request.user.is_authenticated


class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')[:6]
        context = {
            'post_list': post_list,
        }
        return context
    
    
class PostCreate(OnlyPostCreate, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')
    template_name = 'myapp/post_form.html'
    
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)
    
    def get_success_url(self):
        messages.success(self.request, 'New post has beed registered.')
        return resolve_url('myapp:index')
    

class PostDetail(DetailView):
    model = Post
    template_name = 'myapp/post_detail.html'
    
    def get_context_data(self, **kwargs):
        '''
        add things below into the object
        - like flag
        - posts have same category
        '''
        context = super().get_context_data(**kwargs)
        is_liked = Like.objects.filter(user = self.request.user).filter(post = context['object'].pk).count() > 0
        context['is_liked'] = is_liked
        
        category = Post.objects.get(id=self.kwargs['pk']).category
        posts = Post.objects.filter(category = category).exclude(id = self.kwargs['pk']).order_by('-created_at')[:5]
        context['posts'] = posts
        return context


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm 
    
    def get_success_url(self):
        messages.info(self.request, 'The Post has been updated.')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])
    
    
    
class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post
    
    def get_success_url(self):
        messages.info(self.request, 'The Post has been deleted.')
        return resolve_url('myapp:index')
    
    
class PostList(ListView):
    model = Post
    paginate_by  = 6
    
    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')
    
    
class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'

    
class Logout(LogoutView):
    template_name = 'myapp/logout.html'
    
    
class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'Your account has registered successfully.')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def AddLike(request, post_id):
    post = Post.objects.get(id = post_id)
    is_liked = Like.objects.filter(user = request.user).filter(post = post_id).count()
    if is_liked > 0:
        messages.info(request, 'You already liked this post.')
    else:
        like = Like()
        like.user = request.user
        like.post = post
        like.save()
        messages.success(request, 'Added your liked articles!')
    return redirect('myapp:post_detail', post.id)


class CategoryList(ListView):
    model = Category
    template_name = 'myapp/category_list.html'
    
    
class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name'
    slug_url_kwarg = 'name'
    template_name = 'myapp/category_detail.html'
    
    def get_context_data(self, **kwargs):
        category_name = Category.objects.get(name = self.kwargs['name'])
        posts = Post.objects.filter(category = category_name).order_by('-created_at')
        params = {
            'category_name': category_name,
            'posts': posts,
        }
        return params


def SearchPost(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)
        
        if searchform.is_valid():
            search_word = searchform.cleaned_data['search_word']
            posts_hit = Post.objects.filter(Q(title__icontains = search_word)|
                                        Q(content__icontains = search_word))
            is_exist = posts_hit.count() > 0
            
        params = {
            'posts_hit': posts_hit,
            'is_exist': is_exist,
            'search_word': search_word,
        }
        
        return render(request, 'myapp/search.html', params)
    

app/myblog/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{{ request.site.siteconfig.meta_title }}</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <!-- Start your project here-->
    <header>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
          <a class="navbar-brand" href="/" >This me</a>
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarExample01"
            aria-controls="navbarExample01"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarExample01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <!-- Dropdown -->
            <!-- Navbar dropdown -->
            <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              Articles
            </a>
            <!-- Dropdown menu -->
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'myapp:post_list' %}">Articles</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'myapp:category_list' %}">Categories</a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                {% if request.user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'myapp:post_create' %}">New post</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'myapp:login' %}">Sign in</a>
                {% endif %}
              </li>
             </ul>
            </li>
            <!-- Dropdown -->

              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"> {{ request.user }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:logout' %}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:login' %}">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:signup' %}">Sign up</a>
                    </li>
                {% endif %}
            
            </ul>
          </div>
          <form action="{% url 'myapp:search_post' %}" class="d-flex input-group w-auto" method='POST'>
            {% csrf_token %}
            <input
              type="search"
              class="form-control rounded"
              placeholder="Search"
              aria-label="Search"
              aria-describedby="search-addon"
              name="search_word"
            />
            <span class="input-group-text border-0" id="search-addon">
              <i class="fas fa-search"></i>
            </span>
          </form>
        </div>
      </nav>
      <!-- Navbar Second -->
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Toggle button -->
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarCenteredExample"
            aria-controls="navbarCenteredExample"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>
      
          <!-- Collapsible wrapper -->
          <div
            class="collapse navbar-collapse justify-content-center"
            id="navbarCenteredExample"
          >
            <!-- Left links -->
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% for category in categories %}
                <li class="breadcrumb-item">
                  <a href="{% url 'myapp:category_detail' category %}">{{ category }}</a>
                </li>
                {% endfor %}
            </ul>
            <!-- Left links -->
          </div>
          <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
      </nav>
    </header>

    <main class='container'>
    <!-- message -->
    <br>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} col-md-9" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <!-- message -->

    {% block content %}
    {% endblock %}
    </main>
    <footer class="text-center text-white" style="background-color: #f1f1f1;">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-github"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 skimsyk.com
      </div>
      <!-- Copyright -->
    </footer>
    <!-- End your project here-->

    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.js"
    ></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>

app/myblog/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for post in posts %}
  <div class="col">
    <a href="{% url 'myapp:post_detail' post.id %}">
    <div class="card h-100">
      {% if post.thumbnail %}
      <img src="{{ post.thumbnail.url }}" class="card-img-top" alt="{{ post.title }}"/ height="200">
      {% else %}
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="{{ post.title }}"/>
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <div class='text-muted'> 
          <p> {{ post.category }}</p>
          <p> {{ post.content | safe | truncatechars_html:15 }}</p>
          {{ post.created_at }}
          <small> written by {{ post.author }} </small>
        </div>
      </div>
    </a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

app/myblog/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <h2>Category List</h2>
    <br>
    {% for category in category_list %}
    <div>
    <a href="{% url 'myapp:category_detail' category.name %}">{{ category.name }}</a>
    <small> ({{ category.count_posts_belong_to }}) </small>
    <div>
    {% endfor %}
  </div>
</div>

{% endblock %}

app/myblog/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
<!-- Jumbotron -->
<div class="p-5 text-center bg-light">
  <h1 class="mb-3">This is personal blog</h1>
  <h4 class="mb-3">Data viesualization and analysis</h4>

  {% if request.user.is_authenticated %}
  <a class="btn btn-primary" href="{% url 'myapp:post_create' %}" role="button">New post</a>
  {% endif %}
</div>
<!-- Jumbotron -->

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for item in post_list %}
  <div class="col">
    <a href="{% url 'myapp:post_detail' item.id %}">
    <div class="card h-100">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="Hollywood Sign on The Hill"/>
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <div class='text-muted'> 
          {{ item.created_at }}
          <small> written by {{ item.author }} </small>
        </div>
      </div>
    </a>
    </div>
  </div>
  {% endfor %}
</div>
<br>
{% endblock %}

app/myblog/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="col-md-6">
<h2> Login </h2>

<form action="" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
  {% endfor %}
  <br>
  <button type="submit" class="btn btn-outline-dark btn-rounded" data-mdb-ripple-color="dark">Login</button>
</form>
<br>
<div class="col-md-6">

{% endblock %}

app/myblog/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="col-md-6">
<h2> Signed out successfully</h2>
<br>
<div class="col-md-6">

{% endblock %}

app/myblog/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <br>
    <div class="alert alert-danger" role="alert">
      <form method="post">
        {% csrf_token %}
        <p> Do you really want to delete this post?</p>
        <h2>Title : {{ object.title}} </h2>
        <input type="submit" class="btn btn-outline-danger" value="Delete">
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/myblog/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-md-9">
    <br>  
    {% if post.thumbnail %}
      <img src="{{ post.thumbnail.url }}" class="card-img-top" alt="{{ post.title }}" height="400"/>
    {% else %}
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="{{ post.title }}"/>
    {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <p class="small"> {{ object.category }}</p>
        <p class="card-text">{{ object.content | safe | linebreaksbr | urlize }}</p>

        {% if is_liked %}
        <a class="btn" href="{% url 'myapp:addlike' object.pk %}" style="background-color:#13ae4b; color:white">
          Liked
        </a>
        {% else %}
        <a class="btn" href="{% url 'myapp:addlike' object.pk %}" style="background-color:#FF6699; color:white">
          Like
        </a>
        {% endif %}
        </a>

        <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-info">Back</a>

        {% if user.is_authenticated and object.author == user %}
        <div>
          <br>
          <a href="{% url 'myapp:post_update' object.pk %}" type="button" class="btn btn-outline-dark btn-rounded" data-mdb-ripple-color="dark">
            Edit
          </a>
          <a href="{% url 'myapp:post_delete' object.pk %}" type="button" class="btn btn-outline-danger btn-rounded" data-mdb-ripple-color="dark">
            Delete
          </a>
        </div>
        {% endif %}        
    </div>
  </div>
  <div class="col-md-3">
        
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">{{ object.category }}</h5>
            <p> same category post </p>
            <ul class="list-group">
            {% for post in posts %}
            
            <li class="list-group-item">
              <a href="{% url 'myapp:post_detail' post.id %}">
              {{ post.title }}
              </a>
            </li>

            {% endfor %}
            </ul>
        </div>
      </div>

  </div>
</div>
{% endblock %}

app/myblog/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2> New post </h2>
        <br>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Title input -->
            <div class="form-group mb-4">
                <label> Title </label>
                {{ form.title }}
            </div>

            <!-- Category input -->
            <div class="form-group mb-4">
                <label> Category </label>
                {{ form.category }}
            </div>

            <!-- Thumbnail input -->
            <div class="form-group mb-4">
                <label> Thumbnail </label>
                {{ form.thumbnail }}
            </div>

            <!-- Content input -->
            <div class="form-group mb-4">
                <label>Content</label>
                {{ form.content }}
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-dark btn-rounded mb-4">POST</button>

            <a type="button" class="btn btn-light btn-rounded mb-4" href="/">
                Go Back
            </a>
        </form>
    </div>
</div>
{% endblock %}

app/myblog/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6">
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Created at</th>
      </tr>
    </thead>
    <tbody>
        {% for post in post_list %}
          <tr>
            <td>
              <a href="{% url 'myapp:post_detail' post.pk %}">{{ post.title }} </a>
            </td>
            <td>
              {{ post.content | safe | truncatechars_html:20 }}
            </td>
            <td>
              {{ post.created_at }}
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
  </div>

  <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
</div>

{% endblock %}

app/myblog/templates/myapp/search.html
{% extends 'myapp/base.html' %}

{% block content %}
<!-- Jumbotron -->
<div class="p-5 text-center bg-light">
  <h1 class="mb-3">This is personal blog</h1>
  <h4 class="mb-3">Data viesualization and analysis</h4>

  <div>
    <a class="btn btn-primary mb-3" href="{% url 'myapp:post_list' %}" role="button">Articles</a>
  </div>
  {% if request.user.is_authenticated %}
  <div>
  <a class="btn btn-secondary" href="{% url 'myapp:post_create' %}" role="button">New post</a>
  </div>
  {% endif %}
</div>
<!-- Jumbotron -->

{% if is_exist %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for post in posts_hit %}
    <div class="col">
      <a href="{% url 'myapp:post_detail' post.id %}">
      <div class="card h-100">
        {% if post.thumbnail %}
        <img src="{{ post.thumbnail.url }}" class="card-img-top" alt="{{ post.title }}"/>
        {% else %}
        <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="{{ post.title }}"/>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <div class='text-muted'> 
            <p> {{ post.category }}</p>
            {{ post.created_at }}
            <small> written by {{ post.author }} </small>
          </div>
        </div>
      </a>
      </div>
    </div>
    {% endfor %}
    </div>
    <br>
  {% else %}
    <h5 class="mb-3">{{ search_word }}に一致する記事は見つかりませんでした。</h5>
  {% endif %}

{% endblock %}

app/myblog/templates/myapp/signup.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="col-md-6">
<h2> Sign up </h2>

<form action="" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
  {% endfor %}
  <button type="submit" class="btn btn-outline-dark btn-rounded" data-mdb-ripple-color="dark">Sign up</button>
</form>
<br>
<div class="col-md-6">

{% endblock %}